### ISSUE TITLE
Slow performance on mobile devices

### ISSUE THREAD

**Issue by vvo** [algolia/instant-search-demo#11]
We have a performance problem on the instant search demo, try it from any mobile device and typing just on letter should show a very bad performance.

Typing multiple letters and backspace etc.. will show even bad performance.

We need to work on these issues, I have been doing with the help of @bobylito some remotte debugging and found out that the lag comes from the way we render the page.

This is somehow important since we advise people to use the instant search demo while it will give them a very slow mobile experience.

Anyone interested in optimizing performance (@pixelastic?) can contribute to this.

Ways to reproduce:
- run the instant search demo locally (npm install -g http-server, http-server .)
- connect your phone to machine to do [remote debugging with chrome](https://developer.chrome.com/devtools/docs/remote-debugging)
- open the instant search demo on phone
- inspect from your machine
- use the timeline or js profiler to see this:

![2015-05-21-120836_1605x650_scrot](https://cloud.githubusercontent.com/assets/123822/7746386/269942a6-ffb2-11e4-89d4-22de94d8a9cc.png)

Optimization ideas (based on a small profiling session):
- [x] use latest jquery
- [x] lower the number of used jquery plugins, the less the better
- [x] ~~use event delegation where available, as much as possible~~ Already done
- [x] closely watch how are sliders and checkbox initialized, seems to take a looot of time
- [x] maybe do not use any jquery plugin for simple chexboxes, should not be needed
- [x] ~~to be done last but still important, [debounce](http://benalman.com/code/projects/jquery-throttle-debounce/examples/debounce/) the search input triggering searches~~ not a good optimization in the end

**Comment by pixelastic** [comment]
Sure. I'll have a look.

**Comment by kokliKo** [comment]
I'll be happy to give a hand this afternoon too!

**Comment by vvo** [comment]
updated the description of the issue to help setting up and debugging + optimizing

**Comment by vvo** [comment]
Ok done with the help of @pixelastic and @kokliKo. We now have a acceptable performance on most mobile devices.

For "old" devices like 200 bucks android from two years ago then the performance can be bad sometimes and the only way to solve it would be to do some sort of virtual-dom to stop creating too much elements/deleting them.
