### ISSUE TITLE
Uncaught TypeError: algoliaHelper.on is not a function

### ISSUE THREAD

**Issue by tquill** [algolia/instant-search-demo#16]
I'm having an issue integrating this into a rails application.  I've got app.js code copied almost exactly (I'm using handlebars instead of hogan), and the code breaks at this point:

    // Search errors
    algoliaHelper.on('error', function(error) {
      console.log(error);
    });

It says:
> Uncaught TypeError: algoliaHelper.on is not a function

Does anyone know the issue?  My first thought is a conflict with jQuery somewhere, but my app is rather barebones at the moment, and I can't seem to prove that a conflict is the problem.  For reference, I'm running jQuery v2.1.3 as opposed to v2.1.4 in the example... though I don't suspect that would make a difference.

**Comment by tquill** [comment]
Wrapping algoliaHelper.on with the dollar sign and parenthasis fixed it:

    // Search errors
    $(algoliaHelper).on('error', function(error) {
      console.log(error);
    });

**Comment by redox** [comment]
Hey @tquill,

wrapping it with the `$` (jQuery) object will definitely not do the expected behavior. Could you please share how you're instantiating the `algoliaHelper` and which version you're using? You might be using the previous v1 of our helper (packaged with the JS code in the Rails API client).

I recommend you to migrate to our latest JS API client (V3, see the [migration guide](https://github.com/algolia/algoliasearch-client-js/wiki/Migration-guide-from-2.x.x-to-3.x.x)) and the latest helper (V2).

**Comment by tquill** [comment]
redox, I really appreciate the help.  I'm following app.js from this instant-search-demo exactly.  I'm using the same index too, I created a new one called "products" so I can just get this working.  The only change I've made is that I'm using handlebars for templating rather than hogan.

Is this app.js out of date at all?

Also, I've removed the Rails API client and I'm just including these two scripts in-line:

    <script src="//cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js"></script>
    <script src="//cdn.jsdelivr.net/algoliasearch.helper/1/algoliasearch.helper.min.js"></script>

The code seems to work fine all the way until:

    algoliaHelper.on('error', function(error) {
      console.log(error);
    });

That's where it says:

> Uncaught TypeError: algoliaHelper.on is not a function

From the migration guide, this code does seem to return all the objects from the products index:

    algoliaHelper.search('', {}, function(err, content) {
      console.log(err, content);
    });

Any other ideas as to what I'm doing wrong?  I don't need to include the Rails API client do I?  At the moment, the only Algolia related code I'm using now is the app.js script from this "instant-search-demo" and the two cdn scripts I mentioned above in-line.  Again, I really appreciate the help.

**Comment by tquill** [comment]
I figured it out.  I believe it had to do with the load order and using the CDN link for the helper, rather than trying to have it go through the rails asset pipeline.  The algoliasearch.helper needs to come after the algoliasearch, and the algoliasearch.helper doesn't seem to work properly when it's in the asset pipeline.

**Comment by tquill** [comment]
I should also note that I was trying to use the products data from algolia only, I didn't have it as a model in my rails app so I wasn't using the initializer per the alogliasearch-rails documentation.  I think that's another primary reason why it wasn't working.

**Comment by redox** [comment]
OK thanks for the details @tquill; loading it from the assets pipeline shouldn't change anything but I'll try to reproduce it to see what we can do to improve the error message.
