### ISSUE TITLE
facet value "AT&T" displays an HTML entity

### ISSUE THREAD

**Issue by Jerskouille** [algolia/instant-search-demo#19]
Context: with `instantsearch.js`.

Just seen it quickly during the presentation, but I believe it should be easily reproducible.

**Comment by bobylito** [comment]
Tried with the latest live demo and it seems fixed. [Test link](https://demo.algolia.com/instant-search-demo/?q=at%26t&hPP=10&idx=instant_search&p=0&is_v=1). Closing.
