### ISSUE TITLE
IE 8 support?

### ISSUE THREAD

**Issue by msholly** [algolia/instant-search-demo#21]
Does this script only support IE 9 and above? We're getting no functionality on IE8 on our implementation.

**Comment by vvo** [comment]
Hi @msholly to get IE8 support you must include this:

```html
<!--[if lte IE 8]>
  <script src="//cdn.jsdelivr.net/core-js/2/shim.min.js"></script>
<![endif]-->
```

Before any script in your page, let me know how it goes.

**Comment by vvo** [comment]
You will also need to use the V1.x.x of jQuery and not the V2 which is not IE8 compliant

**Comment by vvo** [comment]
It seems it required more changes, you can see the changes here: https://github.com/algolia/instant-search-demo/commit/9748968a4dfb9a7c4eabc94802bb8a47cc006034

Be aware that IE8 will no more be supported by Microsoft in January.

May I ask you if this is an important requirement and how many IE8 visitors do you get?

Thanks

**Comment by msholly** [comment]
Between IE7 and 8, its about 8% of total. Not showstopping, but I've focused instead on pushing them to update with Browser-update.org and showing those visitors the old search we had. As you said, it won't be supported anyways.

**Comment by vvo** [comment]
Thanks for getting back here and for the numbers. Glad you moved with a modern solution. Happy coding!
