### ISSUE TITLE
Issue with pagination

### ISSUE THREAD

**Issue by reinaris** [algolia/instant-search-demo#3]
When you visit the demo page:
http://demos.algolia.com/instant-search-demo/#q=&page=2&manufacturer=Sony

And you press page 3 in the pagination the window location will be set to:
http://demos.algolia.com/instant-search-demo/#

The window location will loose it's current query when you click trough the pagination.
Tested on Chrome Version 42.0.2311.135

**Comment by reinaris** [comment]
I found out it the pagination links are resetting the url to a single hash, see:
https://github.com/algolia/instant-search-demo/blob/master/index.html#L172

Changed this href to `javascript:;`.
Fixed the issue.

**Comment by kokliKo** [comment]
Commit dabdb57ed080d807fb9d7e1f6c86cba52d3fd54b closes #3
Thanks @reinaris
