### ISSUE TITLE
History erratic behavior

### ISSUE THREAD

**Issue by bobylito** [algolia/instant-search-demo#6]
When navigating in the demo, the url does not seem to update correctly, and sometimes will be emptied.

**Comment by kokliKo** [comment]
Hey @bobylito 
I couldn't reproduce the behavior, do you remember how you created the bug?
Thanks!

**Comment by bobylito** [comment]
- type a query in the text field (hoover)
 - click outside the text box, in a empty area so it blur the text field
 - click on a facet (hard good)
-> parameters after the hash is emptied

tested on http://demos.algolia.com/instant-search-demo/
