### ISSUE TITLE
Can't run the push.rb file - command not found

### ISSUE THREAD

**Issue by grantkemp** [algolia/instant-search-demo#75]
Currently when I try run the push.rb file to generate the App.js file - I get an error: 
```
2: from ./dataset_import/push.rb:4:in `<main>'
	1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- algoliasearch (LoadError)
UK00585:instant-se
````

**Comment by Haroenv** [comment]
seems like that script didn't include the gemfile, you need to install the dependencies first: `gem install algoliasearch json open-uri`

**Comment by grantkemp** [comment]
gem install algoliasearch worked for me!

**Comment by Haroenv** [comment]
Will reopen so we remember to add a Gemfile so this works more easily
