### ISSUE TITLE
Searching for "eye" finds "ene" substring

### ISSUE THREAD

**Issue by dandv** [algolia/instant-search-demo#9]
Is this the typo feature maybe?

![image](https://cloud.githubusercontent.com/assets/33569/7718334/bb0fc536-fe63-11e4-9337-bb363b1dad2d.png)

**Comment by kokliKo** [comment]
Hey @dandv 
Yes, it's the typo feature at work. As you can see, the "exact match" word is still ranked higher in the results, which is the expected behavior.
Thanks!

**Comment by dandv** [comment]
Thanks @kokliKo. How can typo tolerance be disabled? Would be interesting to see that among [the FAQs](https://www.algolia.com/doc/faq).

**Comment by kokliKo** [comment]
Sure, that's a great suggestion, I'll work on that!
