### ISSUE TITLE
Uncaught TypeError: placeAutocomplete.configure is not a function

### ISSUE THREAD

**Issue by Pfalbo1** [algolia/instant-search-demo#92]
Hello,
So, I have this problem were the .configure is not a function.
In my .js i'm declaring the placeAutocomplete like this : 
`places_Autocomplete_City = places({
		appId: '------',
		apiKey: '-------',
		container: document.querySelector('#ville'),
		type: 'city',
	});`
and then when i try to reconfigure it i do something like this : 
`places_Autocomplete_City .configure({
		countries: [pays[0]]
	});`
I also try to directly set it behind my declaration : 
`var places_Autocomplete_City = places({
		appId: '------',
		apiKey: '------',
		container: document.querySelector('#ville'),
		type: 'city',
	}).configure({ countries: ['fr'] });`
But i got the same error...
Am i doing something wrong ?
Thanks

**Comment by Haroenv** [comment]
Could you add a code sample of what you are trying? we have a sandbox available to try out here: 

http://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/instantsearch.js
